development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mr_development
  pool: 5
  username: root
  password: google
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mr_test
  pool: 5
  username: root
  password: google
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mr_production
  pool: 5
  username: root
  password: google
  socket: /tmp/mysql.sock
